// Toolbox landing: the four tool screens at six widths in both themes (0095). For each:
// the picker selects it by keyboard, its settings change what it shows, its About link
// is right, nothing overflows, no page errors. Static server on 4173.
import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {writeFileSync,mkdirSync} from 'node:fs';
const out='docs/iterations/pixel-v2/30-toolbox-landing/demos';mkdirSync(out,{recursive:true});
const b=await chromium.launch({executablePath:'/Users/twocakes/Library/Caches/ms-playwright/chromium_headless_shell-1234/chrome-headless-shell-mac-arm64/chrome-headless-shell'});const results=[];
for(const width of [1440,1100,900,700,390,320])for(const theme of ['dark','light']){const c=await b.newContext({viewport:{width,height:1000},reducedMotion:'reduce'});await c.addInitScript(t=>{localStorage.setItem('tim-motion','off');localStorage.setItem('tim-theme',t)},theme);const p=await c.newPage();const errors=[];p.on('pageerror',e=>errors.push(String(e)));await p.goto('http://127.0.0.1:4173/toolbox/');await p.evaluate(()=>document.fonts.ready);await p.locator('.global-footer button').first().waitFor();
for(const tool of ['Lockup','Palette','Specimen','Convert']){const btn=p.locator('.tool-picker button').filter({hasText:tool});await btn.focus();await p.keyboard.press('Enter');assert.equal(await btn.getAttribute('aria-pressed'),'true');
 const readout=p.locator('.demo .readout');
 if(tool==='Lockup'){assert.match(await readout.innerText(),/37 files/i);await p.getByRole('button',{name:'PNG',exact:true}).click();assert.match(await readout.innerText(),/28 files/i);await p.getByRole('switch',{name:/^White/}).focus();await p.keyboard.press('Space');assert.match(await readout.innerText(),/23 files/i);await p.locator('.demo .steps button').nth(2).click();assert.ok((await p.locator('.demo .tree-row').count())>3);assert.match(await p.locator('.demo .tree').innerText(),/README\.txt/);await p.getByRole('button',{name:'Dark preview background',exact:true}).count();}
 if(tool==='Palette'){await p.getByRole('button',{name:/^Acme\.css$/}).click();assert.match(await p.locator('.demo pre').innerText(),/--field: #174c43/);await p.getByRole('button',{name:/^Acme_Swatches\.pdf$/}).click();assert.match(await p.locator('.demo .sheet').innerText(),/HEX #174C43/);await p.getByRole('switch',{name:/^Tokens/}).focus();await p.keyboard.press('Space');assert.equal(await p.locator('.demo .file-row').count(),5);}
 if(tool==='Specimen'){await p.getByRole('combobox',{name:/Display typeface/i}).selectOption('press');assert.match(await p.locator('.demo .sheet').innerText(),/Press Start 2P/);await p.getByRole('button',{name:'Specimen',exact:true}).click();assert.match(await p.locator('.demo .sheet').innerText(),/CHARACTERS/);}
 if(tool==='Convert'){await p.waitForFunction(()=>/kB/i.test(document.querySelector('.demo .figures')?.innerText||''),null,{timeout:15000});await p.getByRole('button',{name:'PNG',exact:true}).click();await p.getByRole('button',{name:'1000',exact:true}).click();await p.waitForFunction(()=>/resized to 750×1000/i.test(document.querySelector('.demo .stack')?.innerText||''),null,{timeout:15000});await p.waitForFunction(()=>!/…/.test(document.querySelector('.demo .toolbar')?.innerText||''),null,{timeout:15000});assert.match(await p.locator('.demo .toolbar').innerText(),/6 files/i);}
 const overflow=await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth);assert.equal(overflow,false,`${width}/${theme}/${tool} overflow`);assert.equal(await p.getByRole('link',{name:new RegExp('^About '+tool+'$','i')}).getAttribute('href'),`/toolbox/${tool.toLowerCase()}/`);
 assert.equal(errors.length,0,errors.join('\n'));
 if([1440,390,320].includes(width))await p.locator('.tool-showcase').screenshot({path:`${out}/${width}-${theme}-${tool}.png`,style:'.nav-chrome { visibility: hidden !important; }'});results.push({width,theme,tool,overflow,errors});}
 await c.close()}
const nojs=await b.newPage({javaScriptEnabled:false,viewport:{width:390,height:844}});await nojs.goto('http://127.0.0.1:4173/toolbox/');assert.equal(await nojs.locator('noscript a').count(),4);await b.close();writeFileSync(`${out}/report.json`,JSON.stringify(results,null,2));console.log('PASS: 48 tool/theme/width states, keyboard selection, live settings, previews and measured sizes; four no-JS links.');
