import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {writeFileSync} from 'node:fs';
const b=await chromium.launch({executablePath:'/Users/twocakes/Library/Caches/ms-playwright/chromium_headless_shell-1234/chrome-headless-shell-mac-arm64/chrome-headless-shell'});
const p=await b.newPage();const errors=[];p.on('pageerror',e=>errors.push(String(e)));
await p.goto('http://127.0.0.1:4173/');
assert.match(await p.locator('meta[property="og:image"]').getAttribute('content'),/home.png$/);
await p.locator('.card').first().click();await p.waitForURL('**/work/parc/');
assert.equal(await p.locator('meta[property="og:image"]').count(),1);assert.match(await p.locator('meta[property="og:image"]').getAttribute('content'),/parc.png$/);
await p.locator('nav a[href="/contact/"]').click();await p.waitForURL('**/contact/');assert.match(await p.locator('meta[property="og:image"]').getAttribute('content'),/contact.png$/);
for(const asset of ['favicon.svg','favicon.ico','apple-touch-icon.png','og/home.png','og/parc.png'])assert.equal((await p.request.get(`http://127.0.0.1:4173/${asset}`)).status(),200);
assert.deepEqual(errors,[]);writeFileSync('docs/iterations/pixel-v2/23-social/navigation.json',JSON.stringify({pass:true,errors,checks:'Client navigation Home → PARC → Contact updates a single OG image; favicon and PNG assets return HTTP 200.'},null,2));await b.close();
