<script lang="ts">
  // Palette: the artwork in the centre, the colours and the outputs in the rail, and
  // the files it writes, each one previewable in place. The CSS, SCSS and tokens text
  // is generated by the app's own exporters (`plan.ts`); the swatch sheet is the app's
  // client-deck page, drawn here in HTML.
  import Arrow from '$lib/components/Arrow.svelte';
  import AppToggle from './AppToggle.svelte';
  import SwatchDot from './SwatchDot.svelte';
  import { css, scss, tokensJSON, aseBytes, hexToOklchString, cmyk, normalizedHex, fileSize, pad2, type PaletteEntry } from './plan';

  let name = $state('Acme');
  let colors = $state<PaletteEntry[]>([{ name: 'Field', hex: '#174c43' }, { name: 'Flare', hex: '#ff683b' }, { name: 'Signal', hex: '#f2d600' }, { name: 'Paper', hex: '#f4f1e7' }]);
  let out = $state({ css: true, tokens: true, ase: true, sheet: true });
  let preview: string | null = $state(null);
  const spare = ['#342a67', '#bbdd96', '#11110e', '#4f8fb0'];
  const token = $derived(name.trim() === '' ? 'Palette' : name.trim().replace(/\s+/g, '_'));
  const files = $derived.by(() => {
    const list: string[] = [];
    if (out.css) list.push(`${token}.css`, `${token}.scss`);
    if (out.tokens) list.push(`${token}.tokens.json`);
    if (out.ase) list.push(`${token}.ase`);
    if (out.sheet) list.push(`${token}_Swatches.pdf`, `${token}_Swatches.png`);
    return list;
  });
  // the preview is held by kind, not by filename, so renaming keeps it open
  const kind = (f: string) => f.replace(token, '');
  const active = $derived(preview && files.find((f) => kind(f) === preview) ? preview : null);
  const text = $derived(active === '.css' ? css(colors) : active === '.scss' ? scss(colors) : active === '.tokens.json' ? tokensJSON(colors) : null);
  const at = (i: number) => colors[i % colors.length].hex;
  const setHex = (i: number, v: string) => { const h = normalizedHex(v); if (h) colors[i].hex = h; };
</script>
<div class="readout lbl"><span class="path">~/Toolbox/Palette</span><span>{colors.length} colors</span></div>
<div class="split">
  <div class="stage">
    <div class="mat art">
      {#if text}
        <div class="artboard plate-light preview"><pre class="body">{text}</pre></div>
      {:else if active === '.ase'}
        <div class="artboard plate-light preview swatches">{#each colors as c (c)}<div class="sw"><span style:background={c.hex}></span><span class="lbl">{c.name || c.hex}</span></div>{/each}<span class="lbl dim">{colors.length} swatches / {fileSize(aseBytes(colors))}</span></div>
      {:else if active}
        <div class="artboard plate-light sheet"><b>{name || 'Palette'}</b>{#each colors as c (c)}<div class="row"><i style:background={c.hex}></i><div><b>{c.name || c.hex.toUpperCase()}</b><span>HEX {c.hex.toUpperCase()}</span><span>OKLCH {hexToOklchString(c.hex).slice(6, -1)}</span><span>CMYK {cmyk(c.hex).map((v) => Math.round(v * 100)).join('-')}</span></div></div>{/each}</div>
      {:else}
        <div class="artboard poster" style:background={at(3)} aria-hidden="true"><i style="left:12%;top:8%;width:30%;height:30%" style:background={at(0)}></i><i style="left:42%;top:8%;width:46%;height:46%" style:background={at(1)}></i><i style="left:12%;top:38%;width:30%;height:16%" style:background={at(1)}></i><i style="left:12%;top:62%;width:24%;height:22%" style:background={at(2)}></i><i style="left:64%;top:62%;width:24%;height:22%" style:background={at(0)}></i><span style:color={at(0)}>less noise.</span></div>
      {/if}
    </div>
    <div class="reel">{#each colors as c (c)}<SwatchDot hex={c.hex} size={16} />{/each}</div>
  </div>
  <div class="rail">
    <section class="rail-section">
      <div class="rail-head lbl dim"><span>Palette</span></div>
      <input class="field-plain body" placeholder="Palette" aria-label="Palette name" bind:value={name} maxlength="24" />
    </section>
    <section class="rail-section">
      <div class="rail-head lbl dim"><span>Colors</span><span>{pad2(colors.length)}</span></div>
      {#each colors as c, i (c)}
        <div class="color-row">
          <span class="swatch-chip" style:background={c.hex} aria-hidden="true"></span>
          <input class="field body hex" aria-label={`Hex for color ${i + 1}`} value={c.hex} onchange={(e) => { setHex(i, e.currentTarget.value); e.currentTarget.value = colors[i].hex; }} />
          <input class="field-plain body" placeholder="Name" aria-label={`Name for color ${i + 1}`} bind:value={c.name} maxlength="16" />
          {#if colors.length > 1}<button type="button" class="btn lbl x" aria-label={`Remove color ${i + 1}`} onclick={() => colors.splice(i, 1)}>x</button>{/if}
        </div>
      {/each}
      {#if colors.length < 6}<button type="button" class="btn lbl" style="align-self:flex-start" onclick={() => colors.push({ name: '', hex: spare[colors.length % spare.length] })}><span class="plus">+</span>Add color</button>{/if}
    </section>
    <section class="rail-section">
      <div class="rail-head lbl dim"><span>Outputs</span></div>
      <AppToggle on={out.css} onchange={(v) => (out.css = v)}><span>CSS / SCSS</span></AppToggle>
      <AppToggle on={out.tokens} onchange={(v) => (out.tokens = v)}><span>Tokens</span></AppToggle>
      <AppToggle on={out.ase} onchange={(v) => (out.ase = v)}><span>ASE</span></AppToggle>
      <AppToggle on={out.sheet} onchange={(v) => (out.sheet = v)}><span>Swatch sheet</span></AppToggle>
    </section>
    <section class="rail-section">
      <div class="rail-head lbl dim"><span>Files</span><span>{pad2(files.length)}</span></div>
      {#each files as f (f)}<button type="button" class="file-row body" aria-pressed={active === kind(f)} onclick={() => (preview = active === kind(f) ? null : kind(f))}><span class="name">{f}</span></button>{/each}
    </section>
  </div>
</div>
<div class="toolbar lbl">
  <button type="button" class="btn lbl" disabled><Arrow dir="left" />Back</button>
  <span class="dim">{files.length} files</span>
  <button type="button" class="cta lbl" disabled title="Export happens in the app">Export<Arrow /></button>
</div>
<style>
.art{width:100%;display:flex;justify-content:center;min-height:320px}
.poster{position:relative;width:240px;height:320px;overflow:hidden}.poster i{position:absolute;display:block}.poster span{position:absolute;left:24px;bottom:16px;font:27px/32px var(--face-text)}
.preview{width:100%;padding:var(--s2) var(--s3);overflow:auto;min-height:304px}
.swatches{display:flex;flex-wrap:wrap;gap:var(--s2);align-content:flex-start}.sw{display:flex;flex-direction:column;gap:var(--s1);width:64px}.sw span:first-child{display:block;height:64px;outline:1px solid var(--rim)}.swatches>.lbl{width:100%;padding-top:var(--s1)}
/* the swatch sheet: the client-deck page, white ground, Helvetica, the one place on the site set without pixel faces */
.sheet{width:100%;padding:var(--s3);font:400 11px/16px 'Helvetica Neue',Helvetica,Arial,sans-serif;color:#737373;-webkit-font-smoothing:auto;display:flex;flex-direction:column;gap:var(--s2)}
.sheet>b{font-size:20px;line-height:24px;color:#121212;padding-bottom:var(--s1)}.sheet .row{display:flex;gap:var(--s2);align-items:flex-start}.sheet .row i{display:block;width:96px;height:56px;border-radius:6px;box-shadow:inset 0 0 0 .5px rgba(0,0,0,.12);flex:none}.sheet .row div{display:flex;flex-direction:column}.sheet .row b{color:#121212;font-size:13px}
.reel{display:flex;gap:var(--s1);align-items:center;min-height:16px}
.color-row{display:flex;align-items:center;gap:var(--s1);min-height:var(--s4)}.color-row .swatch-chip{width:32px;height:32px}.color-row .hex{width:120px;flex:none}.color-row .field-plain{flex:1;min-width:0}.x{padding:var(--s1);opacity:var(--dim)}.x:hover{opacity:1}
@media(max-width:700px){.art{min-height:0}.poster{width:192px;height:256px}.preview{min-height:0}}
@media(max-width:420px){.color-row .hex{width:104px}.sheet .row i{width:64px;height:40px}.sheet{padding:var(--s2)}}
</style>
